apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp-image:latest  # Must match exactly what you built & loaded
          imagePullPolicy: Never       # 🔥 This is the key line
          ports:
            - containerPort: 30