apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp-image:latest  # Correct image name
          imagePullPolicy: Always       # Ensure the image is pulled always
          ports:
            - containerPort: 3000
