apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: todoapp-image:latest  # Loaded into Minikube
          imagePullPolicy: IfNotPresent  # Use local image loaded via minikube image load
          ports:
            - containerPort: 3000
