name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: TodoApp
      run: npm install

    - name: Build application
      working-directory: TodoApp
      run: npm run build

    - name: Start OWASP ZAP scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: 'https://jefdevsecops.netlify.app/'
        fail_action: false
        output: 'zap/zap_report.html'
      continue-on-error: true

    - name: Upload ZAP scan report
      if: always()
      uses: actions/upload-artifact@v3@3b52ce3645d2dc3c9f245e4e8d2cb29270989c82
      with:
        name: zap-report
        path: zap/zap_report.html

    - name: Deploy to Netlify
      working-directory: TodoApp
      run: |
        npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir=.
