on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: TodoApp  # Set the correct path to TodoApp

      - name: Build application
        run: npm run build
        working-directory: TodoApp

  zap_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://jefdevsecops.netlify.app/'  # Update with your site URL
          fail_action: false
          output: 'zap/zap_report.html'
        continue-on-error: true

      - name: Upload ZAP scan report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap/zap_report.html

  deploy:
    needs: zap_scan
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }} \
          NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID }} \
          npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=.
        working-directory: TodoApp  # Use the correct working directory for deployment
